---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data


```{r load, echo=TRUE}
activityData <- read.csv("C:/Users/SuitGeek/Desktop/RepData_PeerAssessment1/activity/activity.csv")
dateDownloaded <- date()
dateDownloaded

```



## What is mean total number of steps taken per day?

```{r meanSteps, echo=TRUE}

activitySteps <- activityData$steps
medianSteps <- median(activitySteps,na.rm="TRUE")
averageSteps <- mean(activitySteps,na.rm="TRUE")
colors = c("red","yellow","green","blue","white","black","cyan","pink","orange")
steps <- tapply(activitySteps,activityData$date,sum,na.rm=TRUE)
hist(steps,breaks=10,col=colors,xlab="Number of Steps")
```

## What is the average daily activity pattern?

```{r meanActivity, echo=TRUE}
library(scales)

activityInterval <- activityData$interval
activityMean <- tapply(activitySteps,activityInterval,mean,na.rm=TRUE)
plot(activityInterval[1:288],activityMean,type="l",xlab="5 Minute Intervals",ylab="Average Steps", col="red")

max <- which.max(activityMean)
max
```

## Imputing missing values

```{r imputeMissing, echo=TRUE}
missingValues <- sum(is.na(activitySteps))
missingValues
```

## Are there differences in activity patterns between weekdays and weekends?

```{r difference, echo=TRUE}


```
